# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rzopv

app: api-indra
# "service" is the name of this project. This will also be added to your AWS resource names.
service: api-indra

provider:
  name: aws
  runtime: nodejs20.x

  environment:
    PLANET_TABLE: ${self:service}-TbPlaneta-${sls:stage}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-TbPlaneta-${sls:stage}


resources:
  Resources:
    TbPlaneta:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-TbPlaneta-${sls:stage}
        AttributeDefinitions:
          - AttributeName: id_planeta
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id_planeta
            KeyType: HASH

functions:
  crearPlaneta:
    handler: src/infrastructure/lambda/PlanetaHandler.crearPlaneta
    name: ${self:service}-crearPlaneta-${sls:stage}
    events:
      - httpApi:
          path: /planeta/crear
          method: post

  obtenerPlaneta:
    handler: src/infrastructure/lambda/PlanetaHandler.obtenerPlaneta
    events:
      - httpApi:
          path: /planeta/obtener
          method: get
